services:
  app:
    image: spa:latest
    depends_on:
      - db
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - spa-network
  
  matching-service:
    image: pkitazos/matching-service:amd64

    networks:
      - spa-network