name: "amps"

services:
  db:
  # TODO migrate to latest
    image: postgres:16
    ports:
      - "127.0.0.1:6565:5432"
    volumes:
      - amps-db-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "amps-db"
      POSTGRES_HOST_AUTH_METHOD: "trust"

    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - amps-network


networks:
  amps-network:

volumes:
  amps-db-data:
