services:
  app:
    image: node:22-alpine 
    command: sh -c "apk add --no-cache libc6-compat openssl && npm install -g pnpm && pnpm install && pnpm prisma generate && pnpm dev"
    working_dir: /app 
    volumes:
      - ../:/app
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_DATABASE_URL=postgresql://root:1234@db:6565/allocation-db
    depends_on:
      db:
        condition: service_healthy
    
    extra_hosts:
        - "host.docker.internal:host-gateway"
        
    networks:
      - spa-network
    
