name: amps

services:
  app:
    image: "ghcr.io/amps-kt/amps-app:main-latest"
    depends_on:
      - db
      - redis

    ports:
      - "127.0.0.1:3000:3000"
    environment:
      VALIDATE_ENV_VARS: "true"

      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}"
      MATCHING_SERVER_URL: ${MATCHING_SERVER_URL}
      FRONTEND_SERVER_URL: ${FRONTEND_SERVER_URL}

      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASSWORD: ${MAIL_PASSWORD}

      MAIL_USE_RATE_LIMIT: "ON"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"

      AUTH_FROM_HEADERS: "ON"

      AUTH_WHITELIST_ENABLED: ${AUTH_WHITELIST_ENABLED}
      AUTH_WHITELIST_EMAILS: ${AUTH_WHITELIST_EMAILS}

      HEADERS_SHIB_GUID: ${HEADERS_SHIB_GUID}
      HEADERS_SHIB_DISPLAY_NAME: ${HEADERS_SHIB_DISPLAY_NAME}
      HEADERS_SHIB_EMAIL: ${HEADERS_SHIB_EMAIL}

    volumes:
      - amps-app-logs:/app/logs/
    networks:
      - amps-network

  matching-service:
    image: "ghcr.io/amps-kt/matching-service:main-latest"
    networks:
      - amps-network

  mail-worker:
    image: "ghcr.io/amps-kt/mail-worker:main-latest"
    depends_on:
      - redis

    environment:
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASSWORD: ${MAIL_PASSWORD}

      REDIS_HOST: "redis"
      REDIS_PORT: "6379"

      MAIL_RATE_LIMIT: ${MAIL_RATE_LIMIT}
      MAIL_RATE_LIMIT_PERIOD_MILLIS: ${MAIL_RATE_LIMIT_PERIOD_MILLIS}

    networks:
      - amps-network

  redis:
    image: "redis:8.6.2"

    ports:
      - "6379:6379"

    networks:
      - amps-network

  db:
    image: postgres:16-alpine
    ports:
      - "127.0.0.1:6565:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: "md5"

    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

    volumes:
      - amps-db-data:/var/lib/postgresql/data/
    networks:
      - amps-network

networks:
  amps-network:

volumes:
  amps-db-data:
  amps-app-logs:
